wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.21
    framework: tensorflow
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      3:
      - 2
      4: 3.7.3
      5: 0.10.21
      8:
      - 1
      - 3
      - 5
activation:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 5
init_method:
  desc: null
  value: random
layer_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.01
n_layers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: adam
weight_decay:
  desc: null
  value: 0
